stages:
  train:
    cmd: python train_mlflow.py --n_estimators 150 --random_state 42
    deps:
      - train_mlflow.py
      - data/train.csv
    outs:
      - artifacts/feature_importances.csv
  train_real:
    cmd: python real_model/experiment_runner.py
    deps:
      - real_model/train_real.py
    outs:
      - real_model/artifacts